### ISSUE TITLE
Can I use this with EmberJS version 1.12?

### ISSUE THREAD

**Issue by kalyankiranb** [adopted-ember-addons/ember-metrics#214]
I tried to use this addon with Ember JS version 1.12 and Node version 6. When I try to start my ember server, I am getting the following error.

`(node:56794) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:56794) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
version: 0.1.12
(node:56794) DeprecationWarning: sys is deprecated. Use util instead.
Could not find watchman, falling back to NodeWatcher for file system events

Cannot read property 'parent' of undefined
TypeError: Cannot read property 'parent' of undefined
    at Class.findHostShim [as _findHost] (/Dev/git/app-prodigy/node_modules/ember-metrics/node_modules/ember-getowner-polyfill/node_modules/ember-factory-for-polyfill/index.js:32:32)
    at Class.importShim [as import] (/Dev/git/app-prodigy/node_modules/ember-metrics/node_modules/ember-getowner-polyfill/node_modules/ember-factory-for-polyfill/index.js:36:24)
    at Class.module.exports.included (/Dev/git/app-prodigy/node_modules/ember-metrics/node_modules/ember-getowner-polyfill/node_modules/ember-factory-for-polyfill/index.js:18:18)
    at EmberApp.<anonymous> (/Dev/git/app-prodigy/node_modules/ember-cli/lib/broccoli/ember-app.js:269:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/Dev/git/app-prodigy/node_modules/ember-cli/lib/broccoli/ember-app.js:264:45)
    at new EmberApp (/Dev/git/app-prodigy/node_modules/ember-cli/lib/broccoli/ember-app.js:228:8)
    at Object.<anonymous> (/Dev/git/app-prodigy/Brocfile.js:5:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
`

**Comment by Turbo87** [comment]
Ember.js v1.12 is no longer supported by the Ember development team
